demoshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name = 'cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('add_js', views.cart_add_js, name='cart_add_js'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),

]

demoshop/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from products.views import all_products, FolderView, product_detail, folder_list
from rest_framework.routers import SimpleRouter

router = SimpleRouter()

router.register('api/folders', FolderView)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', all_products, name='home'),
    path('product/<slug:slug>/', product_detail, name='product_detail'),
    path('folder/<slug:folder_slug>/', folder_list, name='folder_list'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders'))
]

urlpatterns += router.urls

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

demoshop/demoshop/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

demoshop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <meta name="description"
        content="All about meta tags and how to add them to your website."/>
  <meta name="keywords"
        content="meta tags, meta description, meta keywords, SEO, search engine optimization"/>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block titel %}
        Demo Shop Servio
      {% endblock titel %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
          crossorigin="anonymous"/>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css"/>
    <link rel="stylesheet" href="{% static 'main.css' %}" type="text/css" />
    <script src="{% static 'add_and_update_cart.js' %}" type="text/javascript"></script>
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}"/>
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}"/>
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}"/>
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}"/>
    <link rel="mask-icon" href="{% static 'favicon/safari-pinned-tab.svg' %}" color="#5bbad5"/>
    <meta name="msapplication-TileColor" content="#da532c"/>
    <meta name="theme-color" content="#ffffff"/> 
  </head>
  <body class="d-flex flex-column min-vh-100">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Servio Demo Shop</a>

        <div class="order-lg-second flex-grow-1 flex-lg-grow-0 text-end">
          <button class="btn btn d-flex justify-content-center" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
    
            <span class="navbar-toggler-icon d-flex justify-content-center me-1"></span>
          
            <a class="nav-item text-decoration-none link-dark" href="#">MENU</a>
          </button>
        </div>

        
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
            <li class="nav-item">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
              </li>
           

            </li>
            <li class="nav-item">
              <a class="nav-link" href="#!">About</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle"
                 id="navbarDropdown"
                 href="#"
                 role="button"
                 data-bs-toggle="dropdown"
                 aria-expanded="false">All Menu</a>
              <ul class="dropdown-menu"
                  aria-labelledby="navbarDropdown"
                  style="min-width: 300px;">
                <li>
                  <a class="dropdown-item" href="{% url 'home' %}">All Products</a>
                </li>
                <li>
                  <hr class="dropdown-divider" />
                </li>
                {% for item, info in folders %}
                  {% if info.open %}
                    <ul>
                      <li class="tree">{% else %}</li>
                      <li>
                      {% endif %}
                      <a href="{{ item.get_absolute_url }}" class="link-dark">
                        <i class="bi bi-folder-fill">
                        {{ item | title }} </i>
                        <br />
                      </a>
                      
                      {% for close in info.close %}
                      </li>
                    </ul>
                  {% endfor %}
                {% endfor %}
              </ul>
            </li>
          </ul>
          <form id="main_cart" class="d-flex">
            {% with total_items=cart|length %}
             
            <a class="btn btn-outline-dark" href="{% url 'cart:cart_detail' %}">
            
              <i class="bi-cart-fill me-1"></i>
              Cart:
              <span id="cart_len" class="badge bg-dark text-white ms-1 rounded-pill">{{ total_items }}</span>
              
              ₴<span id="cart_sum">{{ cart.get_total_price }}</span>  
            </a>
            

              {% endwith %}
          
          </form>
        </div>
      </div>
    </nav>
    <!-- Header-->
    <header class="bg-dark py-0">
      <div class="container px-4 px-bg-5 my-2">
        <div class="text-center text-white">
          <h1 class="display-4 fw-bolder">Servio demo Shop</h1>
          <p class="lead fw-normal text-white-50 mb-0">Do you hungry?</p>
        </div>
      </div>
    </header>
  
    
    {% comment %} <nav class="navbar">
      <div class="container px-4 px-lg-5"> {% endcomment %}
        
      
        <div class="offcanvas offcanvas-start text-bg-light w-auto" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Servio demo Shop</h5>
            <button type="button" class="btn-close btn-close-black" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
              {% for item, info in folders %}
                  {% if info.open %}
                    <ul>
                      <li class="tree">{% else %}</li>
                      <li>
                      {% endif %}
                      <a href="{{ item.get_absolute_url }}" class="link-dark">
                        <i class="bi bi-folder-fill">
                        {{ item | title }} </i>
                        <br />
                      </a>
                      {% for product in products %}
                        {% if product.folder_id == item.id %}
                          <a href="{{ product.get_absolute_url }}" class="link-dark">
                            <i class="bi bi-file-earmark">
                            {{ product.name | title }} </i>
                            <br />
                          </a>
                        {% endif %}
                      {% endfor %}
                      {% for close in info.close %}
                      </li>
                    </ul>
                  {% endfor %}
                {% endfor %}
            </ul>
          </div>
        </div>
      {% comment %} </div>
    </nav> {% endcomment %}



    <div id="content">
      {% block content %}
      {% endblock content %}
    </div>
    <!-- Footer-->
    <div class="my-0 mt-auto">
      <footer class="py-3 bg-dark">
        <div class="container">
          <p class="m-0 text-center text-white">Copyright © Servio Demo Shop 2022</p>
        </div>
      </footer>
    </div>
  </body>
</html>

demoshop/templates/folder.html
{% extends "./base.html" %}
{% load static %}
{% block content %}
  {% if products %}
    <section class="py-2">
      <div class="container">
        <div class="row row-cols-1 row-cols-xs-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-4 g-3 my-1 justify-content-center">
          {% for product in products %}
            <div class="col">
              <div class="card h-100">
                <!-- Sale badge-->
                <div class="badge bg-dark text-white position-absolute"
                     style="top: 0.5rem; right: 0.5rem">Sale</div>
                <!-- Product image-->
                <div class="img-container">
                  <img class="card-img-top img-fluid img-responsive w-100 mx-auto d-block"
                       src="{{ product.image_url | default_if_none:'#' }}"
                       alt="no image"
                       style="max-height: 200px; min-height: 150px; object-fit: cover"/>
                </div>
                <!-- Product details-->
                <div class="card-body align-items-end d-flex justify-content-center">
                  <div class="text-center">
                    <!-- Product name-->
                    <p class="fw-bolder card-text mb-1 card-title align-self-start">{{ product.name | title }}</p>
                    {% comment %} <h5 class="fw-bolder">{{ product.name | title }}</h5> {% endcomment %}
                    <!-- Product reviews-->
                    
                    <div class="d-flex justify-content-center small text-warning mb-2">
                      <div class="bi-star-fill"></div>
                      <div class="bi-star-fill"></div>
                      <div class="bi-star-fill"></div>
                      <div class="bi-star-fill"></div>
                      <div class="bi-star-fill"></div>
                    </div>
                    <!-- Product price-->
                    <!-- <span class="text-muted text-decoration-line-through">$20.00</span> -->
                    ₴{{ product.price }}
                  
                  </div>
                </div>
                <!-- Product actions-->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                  <div class="container">
                    <div class="row justify-content-around">
                      <div class="col p-1 col-auto align-self-center">
                        <div class="text-center">
                          <button type="button" onclick="this.blur(); add_and_update_cart({{ product.id }})"
                                id="{{ product.id }}"
                                value="{{ product.id }}"
                                class="btn btn-outline-dark mt-auto m-1">
                          Add To Cart
                        </button>
                        </div>
                      </div>
                      <div class="col p-1 col-auto align-self-center">
                        <div class="text-center">
                          <a class="btn btn-outline-dark mt-auto m-1"
                             href="{{ product.get_absolute_url }}">Details</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </section>
  {% else %}
    <div class="container py-2">
      <h4>We are sorry, {{ folder.name }} have no goods...</h4>
    </div>
  {% endif %}

  <script>
    var csrf = "{{ csrf_token }}"
</script>

{% endblock content %}

demoshop/templates/home.html
{% extends "./base.html" %}
{% load static %}
{% block content %}
  <section class="py-2">
    <div class="container">
      <div class="row row-cols-1 row-cols-xs-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-4 g-3 my-1 justify-content-center">
        {% for product in products %}
          <div class="col">
            <div class="card h-100">
              <!-- Sale badge-->
              <div class="badge bg-dark text-white position-absolute"
                   style="top: 0.5rem; right: 0.5rem">Sale</div>
              <!-- Product image-->
              <div class="img-container">
                <img class="card-img-top w-100 img-fluid img-responsive w-100 mx-auto d-block "
                     src="{{ product.image_url | default_if_none:'#' }}"
                     alt="no image"
                     style="max-height: 200px; min-height: 150px; object-fit: cover"/>
              </div>
              <!-- Product details-->
              <div class="card-body align-items-end d-flex justify-content-center">
                <div class="text-center">
                  <!-- Product name-->
                  <p class="fw-bolder card-text mb-1 card-title align-self-start">{{ product.name | title }}</p>
                  {% comment %} <h5 class="fw-bolder">{{ product.name | title }}</h5> {% endcomment %}
                  <!-- Product reviews-->
                  <div class="d-flex justify-content-center small text-warning mb-2">
                    <div class="bi-star-fill"></div>
                    <div class="bi-star-fill"></div>
                    <div class="bi-star-fill"></div>
                    <div class="bi-star-fill"></div>
                    <div class="bi-star-fill"></div>
                  </div>
                  <!-- Product price-->
                  <!-- <span class="text-muted text-decoration-line-through">$20.00</span> -->
                  ₴{{ product.price }}
                </div>
              </div>
              <!-- Product actions-->
              <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="container">
                  <div class="row justify-content-around">
                    <div class="col p-1 col-auto align-self-center">
                      <div class="text-center">
                        <button type="button" onclick="this.blur(); add_and_update_cart({{ product.id }})"
                                id="{{ product.id }}"
                                value="{{ product.id }}"
                                class="btn btn-outline-dark mt-auto m-1"
                                >
                          Add To Cart
                        </button>
                      </div>
                    </div>
                    <div class="col p-1 col-auto align-self-center">
                      <div class="text-center">
                        <a class="btn btn-outline-dark mt-auto m-1"
                           href="{{ product.get_absolute_url }}">Details</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </section>
  
  <script>
    var csrf = "{{ csrf_token }}"
</script>
  
{% endblock content %}

demoshop/templates/index_old.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-all.min.css">
    <script src="https://cdn.metroui.org.ua/v4/js/metro.min.js"></script>
  </head>

  <style>
    ul {
  list-style: none;
  padding: 0;
}
li {
  padding-left: 1.3em;
}
li:before {
  content: "\f07b"; /* FontAwesome Unicode */
  font-family: FontAwesome;
  display: inline-block;
  margin-left: -1.3em; /* same as padding-left set on li */
  width: 1.3em; /* same as padding-left set on li */
}
  </style>


  <body>

    <div class="container">



      {% for item in tree %}
    <li data-role="treeview">
      {{ item.data.name }} <br/>
      {% for product in products %}
      {% if product.folder_id == item.id %}
      {{ product.name }} <br/>
      {% endif %}

      {% endfor %}

      {% if item.children %}
      <ul data-role="treeview">
        {% include "index.html" with tree=item.children %}
      </ul>
      {% endif %}
    </li>
    {% endfor %}

</div>
  </body>
</html>

demoshop/templates/product_detail.html
{% extends "./base.html" %}
{% load static %}

{% block content %}

<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{ product.image_url | default_if_none:'#' }}" alt="no image"></div>
            <div class="col-md-6">
                <div class="small mb-1">{{ product.id }}</div>
                <h1 class="display-5 fw-bolder">{{ product.name | title }}</h1>
                <div class="fs-5 mb-5">
                    {% comment %} <span class="text-decoration-line-through">$45.00</span> {% endcomment %}
                    <p class="price">₴{{ product.price }}</p>
                </div>
                <p class="lead">{{ product.description }}</p>
                <div class="d-flex">
                    {% comment %} <input class="form-control text-center me-3" id="inputQuantity" type="num" value="1" style="max-width: 3rem">
                    <button class="btn btn-outline-dark flex-shrink-0" type="button">
                        <i class="bi-cart-fill me-1"></i>
                        Add to cart
                    </button> {% endcomment %}
                    
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                      {{ cart_product_form }}
                         {% csrf_token %}
                     <input type="submit" value="Add to cart">
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock content %}