demoshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name = 'cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('add_js', views.cart_add_js, name='cart_add_js'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),

]

demoshop/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from products.views import all_products, FolderView, product_detail, folder_list
from rest_framework.routers import SimpleRouter

router = SimpleRouter()

router.register('api/folders', FolderView)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', all_products, name='home'),
    path('product/<slug:slug>/', product_detail, name='product_detail'),
    path('folder/<slug:folder_slug>/', folder_list, name='folder_list'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders'))
]

urlpatterns += router.urls

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

demoshop/demoshop/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

demoshop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),

]

demoshop/cart/models.py
from django.db import models

# Create your models here.

demoshop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

demoshop/cart/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from rest_framework.utils import json

from products.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/cart_detail.html', {'cart': cart})

def cart_add_js(request):
    cart = Cart(request)
    if request.method == 'POST':
        jsondata = json.loads(request.body)
        product_id = jsondata.get('product_id')
        product = get_object_or_404(Product, id=product_id)
        cart.add(product=product)
        response = JsonResponse({'cart_len': cart.__len__(), 'cart_sum': cart.get_total_price()  })
        return response
    return redirect(request.META['HTTP_REFERER'])

demoshop/templates/cart/cart_detail.html
{% extends "../base.html" %}
{% load static %}

{% block title %}
    Your shopping cart
{% endblock title %}


{% block content %}

{% if cart %}

<section class="py-2">
    <div class="container">
<h2>Your shopping cart</h2>
<div class="table-responsive">
    <table class="cart table table-sm">
        <thead class="table-light">
        <tr class="text-center">
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Change Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr class="text-center align-middle">
                    <td class="col-md-2">
                        <a href="{{ product.get_absolute_url }}">
                            <img class="rounded img-responsive mx-auto d-block" src="{{ product.image_url | default_if_none:'#' }}" alt="no image" width="100%" height="100%"/>
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>
                        <form action="{% url 'cart:cart_add' product.id %}" method="post">
                            <div class="container">
                                <div class="row justify-content-center">                                  
                                    <div class="col p-1 col-auto align-self-center">
                                        {{ item.update_quantity_form.quantity }}                                                                   
                                        {{ item.update_quantity_form.update }}                                                                           
                                    </div>
                                    <div class="col p-1 col-auto align-self-center">
                                        <input type="submit" value="Update" class="btn btn-info btn-sm border border-dark"/>
                                        {% csrf_token %}
                                    </div>
                                </div>
                            </div>   
                        </form>
                    </td> 
                    <td><a class="btn btn-danger btn-sm border border-dark" href="{% url "cart:cart_remove" product.id %}">Remove</a></td>
                    <td class="num">₴{{ item.price }}</td>
                    <td class="num">₴{{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total table-light text-center">
          <td><strong>Total</strong></td>
          <td colspan="5"></td>
          <td class="num"><strong>₴{{ cart.get_total_price }}</strong></td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
      <a href="{% url "home" %}" class="btn btn-light border-dark">Continue shopping</a>
      <a href="{% url "orders:order_create" %}" class="btn btn-dark btn-lg border-dark">Checkout</a>
    </p>
</div>
</div>
</section>

{% else %}
<div class="container py-2">
<h4>Your cart is empty...</h4>
<br>
<a type="button" class="btn btn-light border-dark" href="{% url "home" %}">But you can fix it quickly!</a>
</div>
{% endif %}


{% endblock content %}